-- Generated by Oracle SQL Developer Data Modeler 20.2.0.167.1538
--   at:        2021-03-25 13:12:15 EET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE comanda (
    nr_comanda     NUMBER(3) NOT NULL,
    data_comenzii  DATE NOT NULL,
    nr_ospatar     NUMBER(3) NOT NULL,
    nr_masa        NUMBER(2) NOT NULL
);

CREATE UNIQUE INDEX comanda__idx ON
    comanda (
        nr_masa
    ASC );

ALTER TABLE comanda ADD CONSTRAINT comanda_pk PRIMARY KEY ( nr_comanda );

CREATE TABLE detalii_comanda (
    nr_comanda   NUMBER(3) NOT NULL,
    nume_produs  VARCHAR2(50) NOT NULL,
    cantitate    NUMBER(4)
);

ALTER TABLE detalii_comanda ADD CONSTRAINT comanda_produs_pk PRIMARY KEY ( nr_comanda,
                                                                           nume_produs );

CREATE TABLE login (
    username    VARCHAR2(30) NOT NULL,
    parola      VARCHAR2(20) NOT NULL,
    last_login  DATE NOT NULL,
    admin       number(38,0) NOT NULL
);

ALTER TABLE login ADD CONSTRAINT login_pk PRIMARY KEY ( username );

CREATE TABLE masa (
    nr_masa    NUMBER(2) NOT NULL,
    nr_locuri  NUMBER(2) NOT NULL,
    status     VARCHAR2(10) NOT NULL
);

ALTER TABLE masa
    ADD CONSTRAINT status_ck CHECK ( status IN ( 'libera', 'ocupata' ) );

ALTER TABLE masa ADD CONSTRAINT masa_pk PRIMARY KEY ( nr_masa );

CREATE TABLE meniu (
    id_categorie NUMBER(2) NOT NULL,
    categorie VARCHAR2(30) NOT NULL
);

ALTER TABLE meniu ADD CONSTRAINT meniu_pk PRIMARY KEY ( id_categorie );
ALTER TABLE meniu ADD CONSTRAINT meniu_uk UNIQUE (categorie);

CREATE TABLE ospatar (
    nr_ospatar  NUMBER(3) NOT NULL,
    nume        VARCHAR2(50) NOT NULL,
    telefon     NUMBER(12) NOT NULL,
    username    VARCHAR2(30) NOT NULL
);

CREATE UNIQUE INDEX ospatar__idx ON
    ospatar (
        username
    ASC );

ALTER TABLE ospatar ADD CONSTRAINT ospatar_pk PRIMARY KEY ( nr_ospatar );

CREATE TABLE produs (
    nume_produs  VARCHAR2(50) NOT NULL,
    pret         NUMBER(4) NOT NULL,
    gramaj       NUMBER(4) NOT NULL,
    masura       VARCHAR2(10) NOT NULL,
    id_categorie   NUMBER(3) NOT NULL
);

ALTER TABLE produs
    ADD CONSTRAINT masura_ck CHECK ( masura IN ( 'bucata', 'gram', 'litru' ) );

ALTER TABLE produs ADD CONSTRAINT produs_pk PRIMARY KEY ( nume_produs );

ALTER TABLE comanda
    ADD CONSTRAINT comanda_masa_fk FOREIGN KEY ( nr_masa )
        REFERENCES masa ( nr_masa );

ALTER TABLE comanda
    ADD CONSTRAINT comanda_ospatar_fk FOREIGN KEY ( nr_ospatar )
        REFERENCES ospatar ( nr_ospatar );

ALTER TABLE detalii_comanda
    ADD CONSTRAINT comanda_produs_comanda_fk FOREIGN KEY ( nr_comanda )
        REFERENCES comanda ( nr_comanda );

ALTER TABLE detalii_comanda
    ADD CONSTRAINT comanda_produs_produs_fk FOREIGN KEY ( nume_produs )
        REFERENCES produs ( nume_produs );

ALTER TABLE ospatar
    ADD CONSTRAINT ospatar_login_fk FOREIGN KEY ( username )
        REFERENCES login ( username );

ALTER TABLE produs
    ADD CONSTRAINT produs_meniu_fk FOREIGN KEY ( id_categorie )
        REFERENCES meniu ( id_categorie );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             2
-- ALTER TABLE                             15
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
